apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-deploy-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-dir/httpd-pv/
    server: 192.168.120.2
