apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-deploy-pvc
  namespace: demo-deploy
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
